### ISSUE TITLE
external wms request feature on multi object return only one result

### ISSUE THREAD

**Issue by tigerfoot** [ioda-net/geo-front3#120]
With https://map.geoportal.xyz/api/shorten/6e4d8f31fb
Whatever the number of object selected only one result is displayed.

**Comment by tigerfoot** [comment]
On mercredi, 14 septembre 2016 01.21:54 h CEST Julien Enselme wrote:
> Closed #120 via e26f266644bacc613c5204605c278fffb7019e62.

Mot yet deployed :-(

-- 

Bruno Friedmann 
 Ioda-Net Sàrl www.ioda-net.ch
 Bareos Partner, openSUSE Member, fsfe fellowship
 GPG KEY : D5C9B751C4653227
 irc: tigerfoot

**Comment by Jenselme** [comment]
Deployed.
